"""Initial migration

Revision ID: 77fb5ce9d2e1
Revises: 
Create Date: 2025-10-30 22:49:16.637889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fb5ce9d2e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_schedules_id'), table_name='recurring_schedules')
    op.drop_table('recurring_schedules')
    op.drop_index(op.f('ix_pto_blocks_id'), table_name='pto_blocks')
    op.drop_table('pto_blocks')
    op.create_index(op.f('ix_appointment_sessions_actual_start'), 'appointment_sessions', ['actual_start'], unique=False)
    op.create_index(op.f('ix_appointment_sessions_booking_id'), 'appointment_sessions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_appointment_sessions_consumer_id'), 'appointment_sessions', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_appointment_sessions_service_id'), 'appointment_sessions', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointment_sessions_specialist_id'), 'appointment_sessions', ['specialist_id'], unique=False)
    op.create_index(op.f('ix_bookings_client_email'), 'bookings', ['client_email'], unique=False)
    op.create_index(op.f('ix_bookings_client_name'), 'bookings', ['client_name'], unique=False)
    op.create_index(op.f('ix_bookings_consumer_id'), 'bookings', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_bookings_date'), 'bookings', ['date'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_specialist_id'), 'bookings', ['specialist_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_consumers_created_at'), 'consumers', ['created_at'], unique=False)
    op.create_index(op.f('ix_consumers_phone'), 'consumers', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumers_phone'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_created_at'), table_name='consumers')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_specialist_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_consumer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_name'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_email'), table_name='bookings')
    op.drop_index(op.f('ix_appointment_sessions_specialist_id'), table_name='appointment_sessions')
    op.drop_index(op.f('ix_appointment_sessions_service_id'), table_name='appointment_sessions')
    op.drop_index(op.f('ix_appointment_sessions_consumer_id'), table_name='appointment_sessions')
    op.drop_index(op.f('ix_appointment_sessions_booking_id'), table_name='appointment_sessions')
    op.drop_index(op.f('ix_appointment_sessions_actual_start'), table_name='appointment_sessions')
    op.create_table('pto_blocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('specialist_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('end_time', sa.TIME(), nullable=True),
    sa.Column('pto_type', sa.VARCHAR(), nullable=True),
    sa.Column('is_full_day', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pto_blocks_id'), 'pto_blocks', ['id'], unique=False)
    op.create_table('recurring_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('specialist_id', sa.INTEGER(), nullable=True),
    sa.Column('recurrence_type', sa.VARCHAR(), nullable=True),
    sa.Column('days_of_week', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('end_time', sa.TIME(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_schedules_id'), 'recurring_schedules', ['id'], unique=False)
    # ### end Alembic commands ###
